config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  resources :products
  root 'products#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # ./config/routes.rb
  get '/profile', to: "user#show"

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :orderables
    has_many :products, through: :orderables

    def total
        orderables.to_a.sum { |orderable| orderable.total}
    end
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :cart


  def total
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :orderables
    has_many :carts, through: :orderables

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_render_cart
    before_action :initialize_cart

    def set_render_cart
        @render_cart = true
    end

    rescue_from ActionController::Redirecting::UnsafeRedirectError do
        redirect_to root_url
    end

    def initialize_cart
        @cart ||= Cart.find_by(id:session[:cart_id])

        if @cart.nil?
            @cart = Cart.create
            session[:cart_id] = @cart.id
        end
    end
end

app/controllers/auth0_controller.rb
# ./app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
  def callback
    # OmniAuth stores the information returned from Auth0 and the IdP in request.env['omniauth.auth'].
    # In this code, you will pull the raw_info supplied from the id_token and assign it to the session.
    # Refer to https://github.com/auth0/omniauth-auth0#authentication-hash for complete information on 'omniauth.auth' contents.
    auth_info = request.env['omniauth.auth']
    session[:userinfo] = auth_info['extra']['raw_info']

    # Redirect to the URL you want after successful auth
    redirect_to '/profile'
  end

  def failure
    # Handles failed authentication -- Show a failure page (you can also handle with a redirect)
    @error_msg = request.params['message']
  end

  def logout
    reset_session
    redirect_to logout_url
  end

  private

  def logout_url
    request_params = {
      returnTo: 'http://localhost:3000/products',
      client_id: AUTH0_CONFIG['auth0_client_id']
    }

    URI::HTTPS.build(host: AUTH0_CONFIG['auth0_domain'], path: '/v2/logout', query: request_params.to_query).to_s
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController


  def show
    @render_cart = true
  end

  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(product_id: @product.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity: quantity)
    elsif quantity <= 0
      current_orderable.destroy
    else
      @cart.orderables.create(product: @product, quantity: quantity)
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace('cart',
                                                   partial: 'cart/cart',
                                                   locals: { cart: @cart }),
                              turbo_stream.replace(@product)]
      end
    end
  end

  def remove
    Orderable.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('cart',
                                                  partial: 'cart/cart',
                                                  locals: { cart: @cart })
      end
    end
  end
end

app/controllers/concerns/secured.rb
# ./app/controllers/concerns/secured.rb
module Secured
    extend ActiveSupport::Concern
  
    included do
      before_action :logged_in_using_omniauth?
    end
  
    def logged_in_using_omniauth?
      redirect_to '/' unless session[:userinfo].present?
    end
  end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
    @render_cart = false
  end

  # GET /products/1 or /products/1.json
  def show
    @render_cart = false
  end

  # GET /products/new

  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    include Secured
  
    def show
      # session[:userinfo] was saved earlier on Auth0Controller#callback
      @user = session[:userinfo]
    end

  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cart/_cart.html.erb
 <%= turbo_frame_tag "cart" do %>
    <% if @cart.orderables.count > 0 %>
    <%= render "cart/orderables" %>
    <% else %>
    <p> Your cart is empty </p>
   <% end %>
  <% end %>

 

app/views/cart/_orderables.html.erb
 <div id="main-content" class="container h-100">
            <div id="content-home" class="page">
              <div class="text-center">
                <section class="h-100 h-custom" style="background-color: #FFFFFF;">
                    <h1 class="fw-bold mb-0 text-black">Shopping Cart</h1>
                            <% @cart.orderables.each do |orderable| %>
                                <% product = orderable.product%>
                                <div id="<%="cart-#{product.id}" %>">
                                <div style = "display:flex; justify-content:space-between; margin: 2em 5em;">
                                    <strong>Name:</strong>
                                    <%= product.name %>
                                    <strong>Price:</strong>
                                    <%= product.price %>
                                <%= form_with(url:cart_add_path) do |f| %>
                                    <%= f.hidden_field :id, value: product.id %>
                                    <%= f.number_field :quantity, value: orderable.quantity, min: 0 %>
                                    <%= f.submit "Add to Cart" %>
                                <% end %>

                                <%= form_with(url:cart_remove_path) do |f| %>
                                    <%= f.hidden_field :id, value: orderable.id %>
                                    <%= f.submit "X" %>
                                <% end %>

                                <strong>Total:</strong>
                                <%= orderable.total %> 
                                </div>
                            </div>
                            <% end %>
                            </div>
 </div>
  </div>

app/views/cart/show.html.erb
<% @cart.orderables.each do |orderable| %>
  <% product = orderable.product %>
  <p><%= product.name %> * <%= orderable.quantity %> = $<%= product.price * orderable.quantity %></p>
<% end %>

<%if @cart.total > 35%>
      <p> You earned free shipping </p>
     <p> Total: <%= @cart.total%> </p>
     <% else %> 
     <p> Flat rate shipping: $3.99 </p>
    <p>Total: <%= @cart.total + 3.99 %> </p>
 <% end %>
</section> 

app/views/layouts/_navbar.html.erb
 <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
    <%=stylesheet_link_tag :main %>
    <link
      rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/monokai-sublime.min.css"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.7.2/css/solid.css"
      integrity="sha384-r/k8YTFqmlOaqRkZuSiE9trsrDXkh07mRaoGBMoDcmA58OHILZPsk29i2BsFng1B"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.7.2/css/fontawesome.css"
      integrity="sha384-4aon80D8rXCGx9ayDt85LbyUHeMWd3UiBaWliBlJ53yzm9hqN21A+o1pqoyK04h+"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdn.auth0.com/js/auth0-samples-theme/1.0/css/auth0-theme.min.css"
    />
<nav class="navbar navbar-expand-lg bg-white">
  <div class="container-fluid">
    <a class="navbar-brand" href="/products"><%= image_tag "paint.png", style: 'height:30px; width:30px;' %> 
    Artazon</a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 navbar-right" >
        <li class="nav-item">
           <a href="http://localhost:3000/cart" >
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                  <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
            </a>
        </li>
                <li> 
                <%= button_to 'Login', '/auth/auth0', class: "btn btn-primary", method: :post , data: { turbo: "false" } unless session[:userinfo].present?%>
                </li>
                <li>
                <%= button_to 'Logout', 'auth/logout', class: "btn btn-primary", method: :get , data: { turbo: "false" } if session[:userinfo].present?%>
                </li> 
      </ul>
    </div>
  </div>
</nav>

 


            

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Artazon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div id="main-content" class="container md-8">
    <%= render partial: "cart/cart" if @render_cart %>
    <%= yield %>
    
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
 <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                <div class="col-md-6">
                <%= image_tag("#{product.name.downcase}.jpg", alt: "Picture of #{product.name.downcase}.", class: "card-img-top mb-5 mb-md-0", style: "min-width:600px; max-width:700px")%>
                    <div class="col-sm-6">
                        <h1 class="display-5 fw-bolder"><%= product.name %></h1>
                        <div class="fs-5 mb-5">
                            <span>
                              <%= product.price %>
                            </span>
                        </div>
                         <%= product.description%>
                        <div class="d-flex">
                        <%= form_with(url:cart_add_path) do |f| %>
                                <i class="bi-cart-fill me-1"></i>
                                <%= f.hidden_field :id, value: product.id %>
                                <%= f.number_field :quantity, value: 0, min: 1%>
                                <%= f.submit "Add to Cart", class:"btn btn-outline-dark flex-shrink-0" %>
                                <% end %>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
 <%= link_to "Back to products", products_path %>

   </section>

    

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Artazon</title>

  <body>
     <div id="main-content" class="container md-8">
            <div id="content-home" class="page">
              <div class="text-center">
              <div class="card-deck">   
                <% @products.each do |product| %>        
                <div class="card" style="min-width:300px; max-width:300px">
            <%= image_tag("#{product.name.downcase}.jpg", alt: "Picture of #{product.name.downcase}.", class: "card-img-top") %>
                  <div class="card-body">
                    <h5 class="card-title"> <%=product.name %></h5>
                    <p class="card-text"><%=product.description %></p>
                    <p class="card-text"><%=product.price%></p>
                      <%= form_with(url:cart_add_path) do |f| %>
                      <%= f.hidden_field :id, value: product.id %>
                      <%= f.number_field :quantity, value: 0, min: 1 %>
                      <%= f.submit "Add to Cart" %>
                      <% end %>
                </div>
                    <p>
                         <%= link_to "Show this product", product %>
                     </p>
                    </div> 
                  <% end %>
                </div>
             </div>                   
          </div>
      </div>

  <!--footer -->          
  <footer class="bg-light text-center p-5"> 
  <%= image_tag "paint.png", style: 'height:30px; width:30px;' %> 
  <a href="https://www.flaticon.com/free-icons/paint" title="paint icons">Paint icons created by Freepik - Flaticon</a> 


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.auth0.com/js/auth0-spa-js/1.19/auth0-spa-js.production.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js"></script>

    
  </body>
</html>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<%
=begin%>
 <div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div> 
<%
=end%>

app/views/user/show.html.erb
<div class="m-5">
  <h1>Your Profile</h1>
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= @user['given_name'] %></h5>
      <p><%= @user['nickname'] %>
      </p>
      <a href="/products" class="btn btn-primary">Continue Shopping</a>
      <a href="/cart" class="btn btn-primary">Continue to Checkout</a>
    </div>
  </div>
<%
=begin%>
 
 <p class="mt-3">Normalized User Profile:<%= JSON.pretty_generate(@user)%></p>  
<%
=end%>

</div>